spring.sql.init.mode=never
spring.datasource.url=jdbc:h2:file:./src/main/resources/mdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update